import {AResultSet, TResultSet} from "./AResultSet";
import {INamedParams} from "./ATransaction";
import {TExecutor} from "./types";

/**
 * Simplified type of {@link AStatement}
 */
export type TStatement = AStatement<TResultSet>;

/**
 * An object that represents a precompiled SQL statement.
 * A SQL statement is precompiled and stored in a Statement object.
 * This object can then be used to efficiently execute this statement multiple times.
 */
export abstract class AStatement<RS extends AResultSet> {

    public static async executeFromParent<R>(sourceCallback: TExecutor<null, TStatement>,
                                             resultCallback: TExecutor<TStatement, R>): Promise<R> {
        let statement: undefined | TStatement;
        try {
            statement = await sourceCallback(null);
            return await resultCallback(statement);
        } finally {
            if (statement) {
                await statement.dispose();
            }
        }
    }

    /**
     * Example:
     * <pre>
     * const result = await AStatement.executeResultSet(statement, async (resultSet) => {
     *      return await resultSet.getArrays();
     * })}
     * </pre>
     */
    public static async executeResultSet<R>(
        statement: TStatement,
        callback: TExecutor<TResultSet, R>
    ): Promise<R>;

    /**
     * Example:
     * <pre>
     * const result = await AStatement.executeResultSet(statement, [param1, param2], async (resultSet) => {
     *      return await resultSet.getArrays();
     * })}
     * </pre>
     */
    public static async executeResultSet<R>(
        statement: TStatement,
        params: any[] | INamedParams,
        callback?: TExecutor<TResultSet, R>
    ): Promise<R>;

    public static async executeResultSet<R>(
        statement: TStatement,
        params: any[] | INamedParams,
        callback?: TExecutor<TResultSet, R>
    ): Promise<R> {
        if (!callback) {
            callback = params as TExecutor<TResultSet, R>;
        }
        return await AResultSet.executeFromParent(() => statement.executeQuery(params), callback);
    }

    /**
     * Executes the SQL query in this Statement object and returns
     * the ResultSet object generated by the query.
     *
     * @param {any[] | INamedParams | null} params
     * array of parameters or object containing placeholders as keys and parameters as values; optional
     * @returns {Promise<RS extends AResultSet>}
     * a ResultSet object that contains the data produced by the given query;
     * never null
     */
    public abstract async executeQuery(params?: any[] | INamedParams): Promise<RS>;

    /**
     * Executes the SQL query in this Statement object.
     *
     * @param {any[] | INamedParams | null} params
     * array of parameters or object containing placeholders as keys and parameters as values; optional
     */
    public abstract async execute(params?: null | any[] | INamedParams): Promise<void>;

    /**  Releases this Statement object's database and resources */
    public abstract async dispose(): Promise<void>;
}
