import {ABlob} from "./ABlob";
import {AResultSet} from "./AResultSet";
import {INamedParams} from "./ATransaction";
import {TExecutor} from "./types";

/**
 * An object that represents a precompiled SQL statement.
 * A SQL statement is precompiled and stored in a Statement object.
 * This object can then be used to efficiently execute this statement multiple times.
 */
export abstract class AStatement<B extends ABlob = ABlob,
    RS extends AResultSet<B> = AResultSet<B>> {

    public static async executeSelf<R>(selfReceiver: TExecutor<null, AStatement>,
                                       callback: TExecutor<AStatement, R>): Promise<R> {
        let self: undefined | AStatement;
        try {
            self = await selfReceiver(null);
            return await callback(self);
        } finally {
            if (self) {
                await self.dispose();
            }
        }
    }

    /**
     * Example:
     * <pre>
     * const result = await AStatement.executeQueryResultSet(statement, async (resultSet) => {
     *      return await resultSet.getArrays();
     * })}
     * </pre>
     */
    public static async executeQueryResultSet<R>(
        statement: AStatement,
        callback: TExecutor<AResultSet, R>
    ): Promise<R>;

    /**
     * Example:
     * <pre>
     * const result = await AStatement.executeQueryResultSet(statement, [param1, param2], async (resultSet) => {
     *      return await resultSet.getArrays();
     * })}
     * </pre>
     */
    public static async executeQueryResultSet<R>(
        statement: AStatement,
        params: any[] | INamedParams,
        callback?: TExecutor<AResultSet, R>
    ): Promise<R>;

    public static async executeQueryResultSet<R>(
        statement: AStatement,
        params: any[] | INamedParams,
        callback?: TExecutor<AResultSet, R>
    ): Promise<R> {
        if (!callback) {
            callback = params as TExecutor<AResultSet, R>;
        }
        return await AResultSet.executeSelf(() => statement.executeQuery(params), callback);
    }

    /**
     * Executes the SQL query in this Statement object and returns
     * the ResultSet object generated by the query.
     *
     * @param {any[] | INamedParams | null} params
     * array of parameters or object containing placeholders as keys and parameters as values; optional
     * @returns {Promise<RS extends AResultSet>}
     * a ResultSet object that contains the data produced by the given query;
     * never null
     */
    public abstract async executeQuery(params?: any[] | INamedParams): Promise<RS>;

    /**
     * Executes the SQL query in this Statement object.
     *
     * @param {any[] | INamedParams | null} params
     * array of parameters or object containing placeholders as keys and parameters as values; optional
     */
    public abstract async execute(params?: null | any[] | INamedParams): Promise<void>;

    /**  Releases this Statement object's database and resources */
    public abstract async dispose(): Promise<void>;
}
